services:
  - type: web
    name: flask-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app
    envVars:
      - key: DATABASE_URL
        value: postgres://avnadmin:AVNS_O3z9kbbw2LFc1tKyV82@pg-35e910ad-istu-00f2.b.aivencloud.com:17636/defaultdb?sslmode=require
      - key: SECRET_KEY
        generateValue: true
